env:
  global:
    - secure: OSPUl/sF95TloqdzR5S+SPp5FFT5cBSjuiMTrLkpwlRV6jigbhMNFbMF/0lzCEc2CJxZp1DeN2Wah2lxdFZSlW/ic8E4S33tEk085+oYHQMJPoCS68l9M3PjGOkwzhWupoVc+bYPGs1Tl7mFxMd2Nsy3kgPVjizIVWvBpIW+eyPzJu7NmVv9Q0ZCyqvjQGtsqXpdBhCGKTx60RJu3JTCF42fQLizqvI8Cc/n9IgLqD4ISTYR2WKoMsJlvrTtdAWJbzsfajauiIKN+s8UTq8hLq6w2buMw36loun5hC20cSwKBNaQ2+jyrR7OxjA2jmxgQcMKrftqFV4oo/6ETyPtnpZUxjhV+vUQdATytTqmx4rOIMxcnk4fVPfS+M9PM25/dFs3TyLl2mo2n+PV39unFIeNAsarTL6iBvsZGQwhYDUVAFbODTQTBOESo6c+Ium+fazB4h48NFUL3UA3dAUDP9BADYMnywTwywwQ+nuj6jfv7kwmCsyxehChBtRSQSB/3/3/XFMnECYYt0c5SQZPIIog6vFxcKmSOZiX7OkzyYVEbdw2/WkdJ+mD9dyLxouwK4aydI6Um5dDUVqsZSJ2Tb1g25yprhf4AOtVWHbICvKUB2zGZrtp15j24leFasR09Fo9x+uoXA6KFTtOLQ1PSEAr8qvggh3Grl8sxHu1feQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/KADhosts_azet12
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
