env:
  global:
    - secure: K+fIs4jNmjeBhviftJirVa49/6AdHO2del+ZNtHYDSBJeYCG8t07tnSyIyaerfY9pUWX2bkMYgrGTlxm4ztKqP4eCCLJY9usE6Gtw8QhcT+Tg5GRCECVAhEUx0K/dcdRWQwMQWa5Zd9S3ezjjP2pbea62vfhOvWY3m5JaiYPlG9d2PsDWzqeUK6pwXRxAuURYdLJ9r+L0YwACPNTtbe6TuDxY0/p8QEvU+POcAU0dnAYNUPnjrUZvsxDKANvRStjlFCuvvvvPe82TmpqRCl47eXk8DxGq0976/e3PSvoUI2veUgIJuHdnMyMbuJOFjZvpMf+Xvs76zbnb040rrWVBSYweD5YHoXL4G3yKyvDVSRQcOdYaRcWxRM4ZofaM09GgkdYP1KbNFC6zo9lPxIg/5xiH8+ofE4w6b9AtXWxxYl9Lb037y57L3MSpGgd5Ccyt+WDvqV1xBegRtOZuW/FUOIGZwHvc8G/9rd2bt8kI7AOELH3X9YdBwPJtXhB8WAYNJeGMdUnG8cjLpf03/39k8tNhQIfgPlufepP27BVcdc7ZCvKcxa+n7wNbGEuxAA8UQ6GbsN9hYf5EwQi2oxG/v196I/mplHTbf7yD2LCxZBw3zFIJC+qy2klTMCW8+0Ntsi2BdC+s+gZTFrDNS682oFge+EVVoJxf8kFyPhHJIQ=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/KADhosts_azet12
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
