env:
  global:
    - secure: apbou68xfA2rtvzVosMIhlJscLlJsj+mu4RSvm9/4weNPEae0XZ/Fs/4JQwBtQ976zhXzhmSplvxgRt90il+ZT3I9H4efL5T8DH2tGx23oqOpozvo2GEic9hwuBcrYw/sBOr9+zh8pnuTJE9Zkp85X9ju9HPvbOiJa1j/t/MZQVQTVEyA+LRxpr4g1QB6pBgi2Uoa9Fypeqebsy08vp1nnmcozqTFwTiFWld2I90WDH0ad0e/dT2TD1oFpTYfP9IJf2Wy/RCXzQlwvVUHjomVV1mye/SWAJaIdIdZaIgDxnzrbDz4pxDrDMI1jLtoOdn/72qJXeR9FnbUCiSZ0PIQQdupV5gz1eJ8BkRafPIfrrwkA9ihESAr/kx3ZQNq33hx8optkaAMx30JMF0ETlLXNrLRGGe2ysri6rdn2ZaiixIScHg3cCrjCd7U22BwHk3sL4JZucJjvmD6T2+rOlZ69u+PPYu/liA1wOspfPHGJZMW6QjP6oKtPUDjqCrriaVUGvlVg9R19AhxFua2z/609NiovevSdX55CEdQLPnFZ9ZUuGLcQ6Di+plNYT+4ztG5rgQ/nYUGI2ZY69S1oBEQDv/9ogbPZzoK9sZdkyAc7xt9iichE9Yj7b8is7Pg7jvlDnnW85+NI/5gBA8/6zWuQCR6pR0QKdFf8HbMElez5k=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/KADhosts_azet12
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
