env:
  global:
    - secure: iCOFoXhwOPegZi2iPGHpDjpM3xOmYLt8IrHcoUFIgnh3scLccPSsczsLfzbHZx/13sxs1miu5nMVZ5vigoIPBg4w6EEzOgzyqXUwLZlli7O/Oo5/Thl3nIpwUrHfX512U352PaC8Ar2igMzJUOupXYLvToyDysu4HpfoV8AO20tEQr5E03U1RTUv5VOqmXguhx168SIbCCS2mahaIta8YeI68705G6mUHBUGNEShE+T3DUF/tyHyB9A9bJTS5VhEHwrM9T3MkTAfcGaAJH5LMeQPq7YnWk8BYvZ6Qhy3u2TPM5MCfcfuZqpklei9/Wt4O9EAn1Vcnb/PKI2UZQSfHVltYQE8FQA+PazBmFU8yGggeHyyXNAA5i486tNDTbFzVM5wb0oxBBxpM593Vqxgkw+8WP2SJni+9LY28ow7rqAy38t5ySx/kZfDX75elHXfWwuCxD7QzecxGh6EbU8B/OePASL8OhH+aRl+gei0P9luCZ44uHVFzUw7u1wTQ7lgSHhWQShnhwYuYjdrOqduhvbwJtay0L52YrPPvzLfqP7QenHs+tEuRdpZ9Ykm1ahCHj5DapqPC10DPwS8n0x6h2HyoZLjjmLy/mXXmzA0EuWNJLF88zh3n56DaRNZF8n4uc7LI6BIqF3RRpSJvrpERv3qM5i5qj+tllFx5+xxn8A=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/KADhosts_azet12
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
