env:
  global:
    - secure: ONLlSgQuk3ejusjCMIt1DwHmVQTjNT1fBsrLOMdVmd/it4unPS2Hnr3u6+M6MoqhEwYc7Se8iTmT7nDbq3OiAViM4StzOzfL3DURl9wb5d74aA6hq9zZiJFbefslS7/H5fTqTFs6VXfFVJelGUpPyLd+MUrASYCln18jR7ZVfzbTub7t7jmxk6ouR94kYMPAFwPec5/lB6Z6+M89/b1GzeFk+veIYFiW9c0/6CFCArR4FUOHdHgU62T3U8EFdzd/ZSeDcsH6bcbzfi17T3ltssQRbHe3ik7XwBqWY/er2ULivc+GMX0uz6R2DYS97Lmw9riFW66DX4+COCnRGWYauxjEnOyX94fsvD/ODfr75Yqt3uYyEJ8LN3lXPRmr40d/qI1sSo5sLLk7pTxWj45VLpPNmaZNDjLtQiBELByBqutbEx2PSgaAlRwhy9wpungr2IPJmBcj1YDFVrjVZM9tY9KlMKXtfqlGHssfxcqCEzEjGf3JudHRuFkTetNkaxTc00fJSlpAv9le50InoEw7JwCSgDmrI+baMZgloT0KwICsoEqxW3vlQ8+m5haW6LrB/FLMDvSWTSaowyXZ2X1/kDRTXXuJYuRU0o4zvUQVituVfuSwTQ1BM1kzS970BdU4LFkYnsCNxZhi+aXoXQXqnZID6kOAjJMKUMXgLzIBdhw=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/KADhosts_azet12
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
