env:
  global:
    - secure: HAWIbo2IvNzfUfomdLDpKWjKySeNzRgVqjie7MmerZ7C54gPzv8TVLfig55aPOAo3eB9Kl8Xat9msiVnVOm5HymxoYZE6kP9uox83mXiG8WgtpTTDTieLECyHKCZIu6AH2MZbKDSlHuVS2TP0nBbxuVu295B3+6kSEogoD8b0O9I2oSkzQQuPxvEBKL/2DsFvU7MZ+lX5Owt2qMwUzvVdb+PCAgsXWxnLXlB2tIAegxXErRZmmHvtU5FIg4Ht16z6vXiPgoSY12yEdCMxNbECbkMTT70e9OQ2zmNhvd0LEj/tMX+U6ingEzoM0jfcXmbhKbfA5VLrg8PHyvh1HCfuy1KssGbRG5sGSsX7EQ7K7KS6FYZn5YIdi+Sqeg+ygCbOoOkPSAGxbc+/4V4vurhKihk/KpboPIUUO5rQ7kV6Kt3KG48RpMeFNY14SyJxmBWmUsZOi3JedDFRmmLDTyRE8Vfzux9kfVe59oZYHllenuxcExtio1MfPNlQ2OL+JyL53IUaHEvcN0WZkf48offMmHgFSvL0f45XOBP3XeXmlbyXV0G9nLFFuPTIAArpZELLJRPufig36RMUaTYWwvQkKHkH06wqAxfHJqGSnae8fxt0Em9Z1fqzs1aQKS0IK5HRh++qs7V7qyM+L1JVqDNfSGy2GwCvRoxQ0J74wV/Gk8=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/KADhosts_azet12
    - GIT_BRANCH: master

dist: xenial
sudo: required
language: python

python:
  - "3.7"

matrix:
  fast_finish: true

cache:
  - pip

addons:
  apt:
    packages:
      - dos2unix

install:
  - pip3 install --upgrade pip
  - pip3 install requests

script:
  - python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
