env:
  global:
    - secure: iAI7Z6MPVR44OrfGsuAADXq70xYjnOePjE6WcIYDk8gkACFQdFlQe+An20z63ezAYHRAu8xy9WUWOdJ1nZEYEe9YEw4q54jGSGSrRjhMAATVbjxV6GmgagbmzW/y9ZYwv0k/RM5WdDqRF0QQwJt7QdrX94QkSs+X4iPJdT2UB0xxrH43DRCHjBO/oZoDuSUER5quoozQGnGFLWezC2X7+jm1hVc55fcNZscMqc9jhqWzEL3e3lfwrnaG1Vtv7eGKQfOTTyk4CLi3xby9Y5hPeotwJeFUwqOFGoKrR0JA9m7NUM6ehPqlHM9Hr6RbPDqNBvbwIY+Pr7yHKBLvT0ZahwWKhqXT/Hh8EhcShcaHl3WGdD0o9TzFi0kJ/7VKH+69oqqWOMwPOHo4UNAIHc9duX7K1TwWIHnX1ODAH9AGrMDPJzN4QdIpSSrNMN0I5Dd2B4jL9R4bFJ0c6CdpDg6U/6DM/iRR9upXBhq9o4Vu3noxFVspb8iJ4rPjO0znm0sPt0h6i34f4xiUvcVu8iG3QG6/gBxFqCTpF91nRsvpxTxhncz5vHn2MByCbYca7PZ0At9CYdwsopDzsSyjSMm2aTf0RtNjIpiMUTUe0CjdL0OnpJMt4GhW/xxpi9Yn20td2Up7hfSO17RI9ejeDdbdCxArkcP18mK3OGHJT13Cy/4=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/KADhosts_azet12
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
