env:
  global:
    - secure: OBKs3qlphFxshrlWBbvfkW0STkRXF0T8BrR23zvszW/D3Uel72Rp0gJRs6BG19vJc97UlFm9FPKIjIROQxFm4lpxmalDjbo2cCnx80g9m62TdA/lB8OXvHBTeNtMORTlyPlyMDdLbmTmXAs7pXn/gFxf5LiDQn/9+sdRJqR+ZJrWpW5rpHB6nbOnScU2jcdw9Oo0j68MN6dVnxBJjamEBw2TG3HirseDyRNQB2Y+yNPNKfdgUg8eDh0eqhlGd357OMdbk9fv9ypRqKcMARgUrLV3+Yb4ACqe1McviCGiTEi8ntZglGfGnlE9iRyNMVrJSJpuoLUZaYENStl0LSSVaTFiWT7PBjH8R5TrxCnApC6FhNyANmeHmh3chHh8u07YsF6lDuPupntexn5+EL1ojf5oagCrXuDtT0ivFGD7LOkPk0EW1manc1jYDYNWQLmzGj/hKUulR3v9wOkSJsxRLB4DuzGTm36Iq+AuhkhcUWw7m/TsouOwI/wQfmYua36OVhStuc5dM6AamyiIou+pwhGjcf/FKNZXZtWC75PiCUm1qckS5SkDeOD9S3wID7t70r5ArQo8VWNwxJHvvS+T3N7g6ShHMEcgaQmLVqk8JKGWLPFpMMUE8ymPm2kwLKHVhrnsRA/hp/7j6FBPZKUx/bxue8l1vbPX6eohRLBL7S0=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/KADhosts_azet12
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
