env:
  global:
    - secure: aTUbU4HR15DzuETvLjNcWV/vbMFbTyeULYBMSI3QszeIYz54TBQrDapdNshTK1RCY+eVfUv0UuewrNZTUt5gHD3CPWc0Za/n+7fHJWwyl3yffWkm50PehP5rGBOqNvUKLe/A4YM4us5jbjz2FBmDdx5gbf2Ji54vj12g8dBWnGFSb4hNTzpt0BYNk5kEZr/1Vpc1dWRbIDznQvyv9wlAOnwjyqYCg7Szz0gMImBM2yBqWHw+VGDQDINIiQPVCIVp20eAhaK9nSsAKohNLmQEGeoxvSlwm49cRBP8LM9/XYa5FLSqixs0MfwPsUZAM11eHUABACJgOchh4Emd/8ND4x7JzUZKhIwckQ6jeqVJ3e0RgDIM9E6KLcqjBtlClJLaUYGT9Tlr6qpVPffFcZlpyfrWznnHnvWQSXc5KfFFaWnjlrDYUdbKZFwdYdVjbHMLoDb9GJosdJHfX9iiAIXG+LM5HyUIJkklYVyBPs2/W+5bGdSaRsT14GFLTQNn6YNH4/FDZ48baGeu0DOSxTLbjhCVkvQfLyXRbMqggMbOFzS+2OyxbXE8tUKQoF3ilLTRsoO0n4xwWt0yzD7/DwWWRd70ywPPI7QE0pMBWU8oQmwfdIeuloYVrOLbCcsyq48ep2suVZmygzWgbuVI9kHbGYBLYU+/jarurOjALdv2mtA=
    - GIT_NAME: Travis CI
    - GIT_EMAIL: dead-hosts@funilrys.com
    - TRAVIS_REPO_SLUG: Ultimate-Hosts-Blacklist/KADhosts_azet12
    - GIT_BRANCH: master

language: python

python:
  - "3.6"

matrix:
  fast_finish: true

cache:
  - apt
  - pip

sudo: required

before_install:
  - pip3 install colorama
  - sudo apt-get -y install dos2unix

script:
  - pip3 install git+https://github.com/funilrys/PyFunceble.git@dev#egg=PyFunceble && python3 ./update.py

notifications:
  on_success:   change
  on_failure:   always
